Squint
------

__Tired of squinting to keep your focus?__

TIP: If you like Squint and want to share the W00t!, I'm grateful for
https://www.gittip.com/bairuidahu/[tips] or
http://of-vim-and-vigor.blogspot.com/[beverages].

Squint lets you focus on important work without distractions by
zooming in on the current function or visual selection.

Command Line
~~~~~~~~~~~~

* Use `:[range]Squint` to zoom in on a range of lines.
* By default, the range is the current line.
* This supports visual line ranges with the `'<`,`'>` marks.

Normal Mode Commands
~~~~~~~~~~~~~~~~~~~~

* Use `<leader>z` to zoom the current `[[` to `][` range or visual
  selection.
** If you want to map this differently, use `<plug>squint_zoom_in`

* Use `<leader>Z` to zoom back out again.
** If you want to map this differently, use `<plug>squint_zoom_out`

<plug>squint_zoom_in
^^^^^^^^^^^^^^^^^^^^

The normal mode `<plug>squint_zoom_in` can be mapped to suit the
logical default chunk of your current filetype. By default, this uses
the range bounded by `[[` , `][` which is the current function in C
(and through filetype plugins, many other languages too). In
https://github.com/dahu/vim-asciidoc[vim-asciidoc] for instance, this
is the current Heading-bounded section. If you don't want `[[` ,`][`
to be your default chunk range then nmap `<plug>squint_zoom_in` to
operate on the desired range.

Consider, for example, the arguably improbable desire to be able to
zoom in on a range that is 10 lines around the cursor. Adding the
following map to your `$MYVIMRC` will accomplish that:

  nmap <plug>squint_zoom_in :-10,+10 Squint\|norm! 51%<cr>


Vimoutliner Support
~~~~~~~~~~~~~~~~~~~

NOTE: Unlike the built-in hoisting plugin for Vimoutliner, Squint
allows hoisting from within hoists.

* Use `<localleader>h` to hoist the current subtopics.
* Use `<localleader>Z` to de-hoist the current buffer back into its
  source.

[NOTE]
====

* Vim's default `<localleader>` is `\`
* Vimoutliner's default recommended `<localleader>` is `,,`
* To see your current `<localleader>`, type
+
  :echo maplocalleader

====

If you don't want to use `<localleader>h` and `<localleader>Z` for the
hoist and de-hoist operations, they can be configured through
`<plug>squint_votl_hoist` and `<plug>squint_votl_dehoist`
respectively.


Configuration
~~~~~~~~~~~~~

`squint_dir` :: Directory in which to store all squint tempfiles.

* Value:   string
* Default: unset
+
By default, Squint saves tempfiles in the same directory as the file
from which you zoomed. If you want to store all of your squints in one
directory (for easy cleanup, say), add a line like this to your
`$MYVIMRC`

  let g:squint_dir = '~/.vim/squint/'

